version: '3.9'

services:
  core:
#    network_mode: host
    container_name: core
    image: luna-core
    restart: "unless-stopped"
#    build: https://github.com/KirillBuiko/luna-core.git
    build: .
    ports:
      - "${CORE_REST_PORT}:${CORE_REST_PORT}"
      - "${CORE_GRPC_PORT}:${CORE_GRPC_PORT}"
    environment:
      - NODE_ENV=production
      - REST_PORT=${CORE_REST_PORT}
      - GRPC_PORT=${CORE_GRPC_PORT}
      - COMPUTATION_MODELS_STORAGE_HOST=host.docker.internal:5001
      - EXECUTOR_HOST=host.docker.internal:5002
      - GENERATOR_HOST=host.docker.internal:5003
      - INTERPRETER_HOST=host.docker.internal:5004
      - MODULES_STORAGE_HOST=host.docker.internal:5005
      - PLANNER_HOST=host.docker.internal:5006
      - VARIABLES_STORAGE_HOST=host.docker.internal:5007
      - PROGRAMS_STORAGE_HOST=host.docker.internal:5008
      - TASKS_STORAGE_HOST=host.docker.internal:5009
