// Original file: node_modules/luna-proto-files/enums.proto

export const RequestType = {
  UNKNOWN_REQUEST_TYPE: 'UNKNOWN_REQUEST_TYPE',
  VARIABLE: 'VARIABLE',
  VARIABLE_LIST: 'VARIABLE_LIST',
  PROGRAM: 'PROGRAM',
  PROGRAM_GENERATE: 'PROGRAM_GENERATE',
  PROGRAM_EXECUTE: 'PROGRAM_EXECUTE',
  PROGRAM_INTERPRET: 'PROGRAM_INTERPRET',
  TASK: 'TASK',
  TASK_LIST: 'TASK_LIST',
  TASK_PLAN: 'TASK_PLAN',
  COMPUTATIONAL_MODEL: 'COMPUTATIONAL_MODEL',
  COMPUTATIONAL_MODEL_LIST: 'COMPUTATIONAL_MODEL_LIST',
  CODE_FRAGMENT: 'CODE_FRAGMENT',
  CODE_FRAGMENT_LIST: 'CODE_FRAGMENT_LIST',
  CODE_FRAGMENT_INFO: 'CODE_FRAGMENT_INFO',
  CODE_FRAGMENT_PLUGIN: 'CODE_FRAGMENT_PLUGIN',
  CODE_FRAGMENT_PLUGINS_LIST: 'CODE_FRAGMENT_PLUGINS_LIST',
  CODE_FRAGMENT_PLUGIN_PROCEDURE: 'CODE_FRAGMENT_PLUGIN_PROCEDURE',
} as const;

export type RequestType =
  | 'UNKNOWN_REQUEST_TYPE'
  | 0
  | 'VARIABLE'
  | 2
  | 'VARIABLE_LIST'
  | 4
  | 'PROGRAM'
  | 52
  | 'PROGRAM_GENERATE'
  | 54
  | 'PROGRAM_EXECUTE'
  | 56
  | 'PROGRAM_INTERPRET'
  | 58
  | 'TASK'
  | 102
  | 'TASK_LIST'
  | 104
  | 'TASK_PLAN'
  | 106
  | 'COMPUTATIONAL_MODEL'
  | 152
  | 'COMPUTATIONAL_MODEL_LIST'
  | 154
  | 'CODE_FRAGMENT'
  | 202
  | 'CODE_FRAGMENT_LIST'
  | 204
  | 'CODE_FRAGMENT_INFO'
  | 206
  | 'CODE_FRAGMENT_PLUGIN'
  | 208
  | 'CODE_FRAGMENT_PLUGINS_LIST'
  | 210
  | 'CODE_FRAGMENT_PLUGIN_PROCEDURE'
  | 212

export type RequestType__Output = typeof RequestType[keyof typeof RequestType]
