POST http://{{host}}:5051/api/v1/set
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data;name="info"
Content-Type: application/json

{
  "requestType": "VAR",
  "dataType": "JSON",
  "dataValueType": "var",
  "var": {
    "getInfo1": {
      "id": "66543efbebf6c48a24c8f5b7"
    },
    "value": {
      "name": "core-test-5",
      "type": "string",
      "value": "54321"
    }
  }
}
