POST http://{{host}}:5051/api/v2/var-storage/value
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data;name="data"
Content-Type: application/octet-stream

{
  "test": "json"
}
